# GRYPS Search Console one-time setup (Windows)
# Does not touch repo .env / .env.local - writes to %USERPROFILE%\.config\gryps\
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/seo/setup-gsc.ps1
#   powershell -ExecutionPolicy Bypass -File scripts/seo/setup-gsc.ps1 -Pull

param(
  [switch]$Pull,
  [string]$SiteUrl = "https://gryps.vercel.app/"
)

$ErrorActionPreference = "Stop"
$configDir = Join-Path $env:USERPROFILE ".config\gryps"
$keyPath = Join-Path $configDir "gsc-service-account.json"
$envPath = Join-Path $configDir "seo.env"

New-Item -ItemType Directory -Force -Path $configDir | Out-Null

Write-Host ""
Write-Host "GRYPS - Search Console API setup" -ForegroundColor Cyan
Write-Host "Credentials stay outside the repo: $configDir"
Write-Host ""

Write-Host "Step 1 - Enable Search Console API (browser)"
Write-Host "  https://console.cloud.google.com/apis/library/searchconsole.googleapis.com"
Start-Process "https://console.cloud.google.com/apis/library/searchconsole.googleapis.com"

Write-Host ""
Write-Host "Step 2 - Service account JSON key"
Write-Host "  If you already have a Google service-account key (any SA), paste its path when asked."
Write-Host "  Or create one: https://console.cloud.google.com/iam-admin/serviceaccounts"
Write-Host ""
Write-Host "Default key path:"
Write-Host "  $keyPath" -ForegroundColor Yellow
Write-Host ""

if (-not (Test-Path $keyPath)) {
  while (-not (Test-Path $keyPath)) {
    Write-Host "Key not found yet. Paste full path to your SA JSON (or Enter to re-check default path)."
    $alt = Read-Host "Key path"
    if ($alt -and (Test-Path $alt)) {
      Copy-Item -LiteralPath $alt -Destination $keyPath -Force
      break
    }
    if (Test-Path $keyPath) { break }
    Start-Sleep -Seconds 1
  }
} else {
  Write-Host "Found existing key at default path." -ForegroundColor Green
}

$sa = Get-Content -LiteralPath $keyPath -Raw | ConvertFrom-Json
$saEmail = $sa.client_email
if (-not $saEmail) { throw "JSON key missing client_email" }

Write-Host ""
Write-Host "Service account email:" -ForegroundColor Green
Write-Host "  $saEmail"
try { Set-Clipboard -Value $saEmail } catch { }

Write-Host ""
Write-Host "Step 3 - Confirm this email is Restricted on property: $SiteUrl"
Write-Host "  (You said it is already added - press Enter to continue.)"
Read-Host "Press Enter to write env and continue"

$envLines = @(
  "# Generated by scripts/seo/setup-gsc.ps1 - do not commit"
  "GSC_SITE_URL=$SiteUrl"
  "GSC_CREDENTIALS_PATH=$keyPath"
)
$envLines | Set-Content -LiteralPath $envPath -Encoding utf8

[Environment]::SetEnvironmentVariable("GSC_SITE_URL", $SiteUrl, "User")
[Environment]::SetEnvironmentVariable("GSC_CREDENTIALS_PATH", $keyPath, "User")
$env:GSC_SITE_URL = $SiteUrl
$env:GSC_CREDENTIALS_PATH = $keyPath

Write-Host ""
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "Set User env GSC_SITE_URL + GSC_CREDENTIALS_PATH"

if ($Pull) {
  Write-Host ""
  Write-Host "Running npm run seo:gsc ..."
  Push-Location (Resolve-Path (Join-Path $PSScriptRoot "..\.."))
  try {
    npm run seo:gsc
    if ($LASTEXITCODE -ne 0) { throw "seo:gsc failed" }
    npm run seo:propose
    if ($LASTEXITCODE -ne 0) { throw "seo:propose failed" }
  } finally {
    Pop-Location
  }
} else {
  Write-Host ""
  Write-Host "Next:"
  Write-Host "  npm run seo:gsc"
  Write-Host "  npm run seo:propose"
  Write-Host "Or re-run with -Pull"
}
