# GRYPS Search Console one-time setup (Windows)
# Does not touch repo .env / .env.local — writes to %USERPROFILE%\.config\gryps\
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/seo/setup-gsc.ps1
#   powershell -ExecutionPolicy Bypass -File scripts/seo/setup-gsc.ps1 -Pull

param(
  [switch]$Pull,
  [string]$SiteUrl = "https://gryps.vercel.app/"
)

$ErrorActionPreference = "Stop"
$configDir = Join-Path $env:USERPROFILE ".config\gryps"
$keyPath = Join-Path $configDir "gsc-service-account.json"
$envPath = Join-Path $configDir "seo.env"

New-Item -ItemType Directory -Force -Path $configDir | Out-Null

Write-Host ""
Write-Host "GRYPS · Search Console API setup" -ForegroundColor Cyan
Write-Host "Credentials stay outside the repo: $configDir"
Write-Host ""

Write-Host "Step 1 — Enable Search Console API (browser)"
Write-Host "  https://console.cloud.google.com/apis/library/searchconsole.googleapis.com"
Start-Process "https://console.cloud.google.com/apis/library/searchconsole.googleapis.com"

Write-Host ""
Write-Host "Step 2 — Create service account + JSON key"
Write-Host "  https://console.cloud.google.com/iam-admin/serviceaccounts"
Write-Host "  Create SA (e.g. gryps-gsc-reader) → Keys → Add key → JSON"
Start-Process "https://console.cloud.google.com/iam-admin/serviceaccounts"

Write-Host ""
Write-Host "Save/move the downloaded JSON to:"
Write-Host "  $keyPath" -ForegroundColor Yellow
Write-Host ""

while (-not (Test-Path $keyPath)) {
  Write-Host "Waiting for key file... (paste path if different, or press Enter to re-check)"
  $alt = Read-Host "Key path"
  if ($alt -and (Test-Path $alt)) {
    Copy-Item $alt $keyPath -Force
    break
  }
  if (Test-Path $keyPath) { break }
  Start-Sleep -Seconds 2
}

$sa = Get-Content $keyPath -Raw | ConvertFrom-Json
$saEmail = $sa.client_email
if (-not $saEmail) { throw "JSON key missing client_email" }

Write-Host ""
Write-Host "Service account email:" -ForegroundColor Green
Write-Host "  $saEmail"
Set-Clipboard -Value $saEmail -ErrorAction SilentlyContinue
Write-Host "  (copied to clipboard if allowed)"

Write-Host ""
Write-Host "Step 3 — Add that email in Search Console → Users"
Write-Host "  Property must be: $SiteUrl"
Write-Host "  Settings → Users and permissions → Add user → Restricted"
Start-Process "https://search.google.com/search-console/users?resource_id=$([uri]::EscapeDataString($SiteUrl))"

Write-Host ""
Read-Host "Press Enter after the service account is added in Search Console"

@"
# Generated by scripts/seo/setup-gsc.ps1 — do not commit
GSC_SITE_URL=$SiteUrl
GSC_CREDENTIALS_PATH=$keyPath
"@ | Set-Content -Path $envPath -Encoding UTF8

# User-level env for new shells (does not modify repo .env*)
[Environment]::SetEnvironmentVariable("GSC_SITE_URL", $SiteUrl, "User")
[Environment]::SetEnvironmentVariable("GSC_CREDENTIALS_PATH", $keyPath, "User")
$env:GSC_SITE_URL = $SiteUrl
$env:GSC_CREDENTIALS_PATH = $keyPath

Write-Host ""
Write-Host "Wrote $envPath" -ForegroundColor Green
Write-Host "Set User env GSC_SITE_URL + GSC_CREDENTIALS_PATH"

if ($Pull) {
  Write-Host ""
  Write-Host "Running npm run seo:gsc ..."
  Push-Location (Resolve-Path (Join-Path $PSScriptRoot "..\.."))
  try {
    npm run seo:gsc
    if ($LASTEXITCODE -ne 0) { throw "seo:gsc failed" }
    npm run seo:propose
    if ($LASTEXITCODE -ne 0) { throw "seo:propose failed" }
  } finally {
    Pop-Location
  }
} else {
  Write-Host ""
  Write-Host "Next:"
  Write-Host "  npm run seo:gsc"
  Write-Host "  npm run seo:propose"
  Write-Host "Or re-run: powershell -ExecutionPolicy Bypass -File scripts/seo/setup-gsc.ps1 -Pull"
}
